<a href="https://colab.research.google.com/github/DevendraaK/Machine-Learning-and-Deep-Learning-Projects-/blob/main/riga_re.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving riga_re.csv to riga_re.csv

In [ ]:
df=pd.read_csv('riga_re.csv')

In [ ]:
df.shape

(4689, 13)

In [ ]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
df.head()

,op_type,district,street,rooms,area,floor,total_floors,house_seria,house_type,condition,price,lat,lon
0,For rent,Purvciems,Dzelzavas 93,1,27.0,3.0,5.0,LT proj.,Brick-Panel,All amenities,250.0,56.955484,24.202139
1,For rent,Ziepniekkalns,Ozolciema 32,2,50.0,7.0,9.0,602.,Panel,All amenities,300.0,56.899798,24.098350
2,For sale,centrs,Ieroču 6,2,33.0,1.0,2.0,P. kara,Wood,Partial amenities,13500.0,56.975092,24.139884
3,For sale,Ķengarags,Maskavas 305,2,50.0,5.0,5.0,LT proj.,Panel,All amenities,34000.0,56.859788,24.308342
4,For rent,Teika,Zemgala gatve 80,3,76.0,3.0,12.0,Jaun.,Masonry,All amenities,490.0,56.977745,24.166042

In [ ]:
missing_value_per=(df.isnull().sum()/df.shape[0])*100
missing_value_per

op_type          0.000000
district         0.319898
street           9.639582
rooms            4.030710
area             7.762849
floor            7.101727
total_floors     7.336319
house_seria      9.426317
house_type       9.596929
condition        8.658563
price           10.023459
lat              4.414587
lon              4.414587
dtype: float64

In [ ]:
missing_value_clm_gre_20=missing_value_per[missing_value_per>20].keys()
missing_value_per

op_type          0.000000
district         0.319898
street           9.639582
rooms            4.030710
area             7.762849
floor            7.101727
total_floors     7.336319
house_seria      9.426317
house_type       9.596929
condition        8.658563
price           10.023459
lat              4.414587
lon              4.414587
dtype: float64

In [ ]:
missing_value_clm_gre_20=['street','area','floor','total_floors','house_seria','house_type','condition','lat']
df2_drop_clm = df.drop(columns=missing_value_clm_gre_20)

In [ ]:
df2_drop_clm.shape

(4689, 5)

In [ ]:
df3_num=df2_drop_clm.select_dtypes(include=['int64','float64'])
df3_num.shape

(4689, 2)

In [ ]:
df3_num.isnull().sum()

price    470
lon      207
dtype: int64

In [ ]:
num_var_miss=['price','lon']

In [ ]:
df3_num[num_var_miss][df3_num[num_var_miss].isnull().any(axis=1)]

         price        lon
7        240.0        NaN
42         NaN  11.048029
48         NaN  11.048029
49         NaN  11.048029
51         NaN  11.048029
62     27500.0        NaN
68     44000.0        NaN
69      6790.0        NaN
74     45500.0        NaN
76       450.0        NaN
80         NaN  11.048029
81         NaN  11.048029
91     39000.0        NaN
95         NaN  11.048029
124    74900.0        NaN
138        NaN  11.048029
139        NaN  11.048029
140        NaN  11.048029
141        NaN  11.048029
142        NaN  11.048029
148        NaN  11.048029
150        NaN  11.048029
158    22000.0        NaN
183      220.0        NaN
193      500.0        NaN
194        NaN  11.048029
195    65000.0        NaN
196        NaN  24.053909
203        NaN  11.048029
215      270.0        NaN
216      950.0        NaN
226      350.0        NaN
227      260.0        NaN
231      250.0        NaN
263        NaN  24.308342
270        NaN  11.048029
290      240.0        NaN
313      330.0        NaN
317        NaN  11.048029
337        NaN  11.048029
338        NaN  11.048029
339        NaN  11.048029
340        NaN  11.048029
341        NaN  11.048029
344        NaN  11.048029
355   270000.0        NaN
379        NaN  11.048029
395      250.0        NaN
404        NaN  11.639683
428        NaN  11.048029
441        NaN  11.048029
463        NaN  11.048029
464        NaN  11.048029
470        NaN  11.048029
483        NaN  24.098253
486      280.0        NaN
499        NaN  11.048029
507    40000.0        NaN
512        NaN  11.048029
538    39900.0        NaN
550        NaN  11.048029
551        NaN  24.225406
552        NaN  11.048029
556      230.0        NaN
575      310.0        NaN
580        NaN  11.048029
581        NaN  11.048029
583        NaN  11.048029
584        NaN  11.048029
592        NaN  11.048029
593        NaN  11.048029
594        NaN  11.048029
595        NaN  11.048029
596        NaN  11.048029
597        NaN  11.048029
598     1000.0        NaN
607      250.0        NaN
616        NaN  11.048029
621        NaN  11.048029
623   110000.0        NaN
628        NaN  11.048029
634        NaN  11.048029
652        NaN  11.048029
653      650.0        NaN
662        NaN  11.048029
678        NaN  11.048029
685    62000.0        NaN
686        NaN  24.198562
692      400.0        NaN
708      180.0        NaN
734        NaN  11.048029
738        NaN  11.048029
739        NaN  11.048029
751      120.0        NaN
752    73000.0        NaN
779    54300.0        NaN
782        NaN  11.048029
808        NaN  24.136366
819   333000.0        NaN
821        NaN  11.048029
822        NaN  11.048029
823        NaN  11.048029
824        NaN  11.048029
835        NaN  11.048029
853    45900.0        NaN
860        NaN  11.048029
861        NaN  11.048029
862        NaN  11.048029
863        NaN  11.048029
864        NaN  11.048029
882        NaN  11.048029
930   199500.0        NaN
934    15999.0        NaN
948     1600.0        NaN
960        NaN  11.048029
961        NaN  11.048029
962        NaN  11.048029
975      300.0        NaN
1004     190.0        NaN
1007       NaN  11.048029
1017   57850.0        NaN
1020   17500.0        NaN
1024     850.0        NaN
1032   84000.0        NaN
1041       NaN  11.048029
1042       NaN  11.048029
1043       NaN  11.048029
1044       NaN  11.048029
1052   34500.0        NaN
1053       NaN  24.085765
1054     600.0        NaN
1071     300.0        NaN
1078   56999.0        NaN
1100       NaN  11.048029
1101       NaN  11.048029
1103   48000.0        NaN
1104  147000.0        NaN
1136       NaN  11.048029
1138     500.0        NaN
1156    1100.0        NaN
1158   27990.0        NaN
1159   51000.0        NaN
1164   40800.0        NaN
1166       NaN  11.048029
1169  190000.0        NaN
1171   54990.0        NaN
1189       NaN  11.048029
1221   34500.0        NaN
1222   64000.0        NaN
1227       NaN  11.048029
1235     330.0        NaN
1238       NaN  11.048029
1247     550.0        NaN
1256   45200.0        NaN
1264     420.0        NaN
1265     350.0        NaN
1274  158000.0        NaN
1277   84000.0        NaN
1278   58500.0        NaN
1330   24000.0        NaN
1341       NaN  11.048029
1347   64000.0        NaN
1358       NaN  11.048029
1359       NaN  11.048029
1360       NaN  11.048029
1361       NaN  11.048029
1362       NaN  11.048029
1363       NaN  11.048029
1365       NaN  11.048029
1366       NaN  11.048029
1367       NaN  11.048029
1369       NaN  11.048029
1381       NaN  11.048029
1382       NaN  11.048029
1383       NaN  11.048029
1384       NaN  11.048029
1385       NaN  11.048029
1405       NaN  11.048029
1411       NaN  11.048029
1412       NaN  11.048029
1413       NaN  11.048029
1414       NaN  11.048029
1415       NaN  11.048029
1416       NaN  11.048029
1417       NaN  11.048029
1418       NaN  11.048029
1426       NaN  11.048029
1427   43900.0        NaN
1431     650.0        NaN
1439       NaN  11.048029
1440  270000.0        NaN
1463   36400.0        NaN
1473       NaN  11.048029
1475       NaN  11.048029
1476       NaN  11.048029
1482       NaN  11.048029
1484   20500.0        NaN
1485   43900.0        NaN
1488  275000.0        NaN
1497       NaN  11.048029
1517       NaN  24.018063
1518       NaN  11.048029
1535       NaN  11.048029
1538       NaN  11.048029
1540   72000.0        NaN
1551       NaN  11.048029
1564       NaN  11.048029
1565       NaN  11.048029
1566       NaN  11.048029
1568       NaN  11.048029
1576       NaN  11.048029
1580       NaN  11.048029
1581       NaN  11.048029
1582       NaN  11.048029
1591   55000.0        NaN
1592     350.0        NaN
1595       NaN  11.048029
1605       NaN  11.048029
1606       NaN  11.048029
1607       NaN  11.048029
1608       NaN  11.048029
1609       NaN  11.048029
1610       NaN  11.048029
1611       NaN  11.048029
1612       NaN  11.048029
1613       NaN  11.048029
1622       NaN  11.048029
1630       NaN  11.048029
1634   27300.0        NaN
1636     900.0        NaN
1698       NaN  24.008205
1704  110625.0        NaN
1719       NaN  11.048029
1728   33800.0        NaN
1741       NaN  24.110703
1763     950.0        NaN
1797   43400.0        NaN
1798  140000.0        NaN
1803       NaN  11.048029
1810       NaN  11.048029
1811       NaN  11.048029
1812       NaN  11.048029
1820   72000.0        NaN
1823       NaN  11.048029
1827  225000.0        NaN
1828  169000.0        NaN
1830   38000.0        NaN
1833       NaN  11.048029
1861   59900.0        NaN
1872       NaN  11.048029
1877       NaN  24.170329
1892       NaN  11.048029
1893       NaN  11.048029
1895   45000.0        NaN
1907   43000.0        NaN
1921       NaN  11.048029
1927      30.0        NaN
1931  228000.0        NaN
1967       NaN  11.048029
1977   12000.0        NaN
1979       NaN  11.048029
1981     250.0        NaN
1996       NaN  11.048029
2003  267960.0        NaN
2005   99900.0        NaN
2017       NaN  11.048029
2025  220500.0        NaN
2026  127700.0        NaN
2027  399000.0        NaN
2028       NaN  11.048029
2029       NaN  11.048029
2043       NaN  11.048029
2044       NaN  11.048029
2045       NaN  11.048029
2046       NaN  11.048029
2084       NaN  11.048029
2085       NaN  11.048029
2086       NaN  11.048029
2112       NaN  11.048029
2113       NaN  11.048029
2114       NaN  11.048029
2115       NaN  11.048029
2116       NaN  11.048029
2117       NaN  11.048029
2118       NaN  11.048029
2134       NaN  11.048029
2137       NaN  11.048029
2138       NaN  11.048029
2144       NaN  11.048029
2153       NaN  11.048029
2155       NaN  11.048029
2163   31500.0        NaN
2217       NaN  11.048029
2220     310.0        NaN
2233       NaN  11.048029
2234       NaN  11.048029
2235       NaN  11.048029
2237       NaN  11.048029
2238       NaN  11.048029
2239       NaN  11.048029
2240       NaN  11.048029
2241       NaN  11.048029
2242       NaN  11.048029
2246   76999.0        NaN
2250   65000.0        NaN
2261       NaN  11.048029
2266   84300.0        NaN
2276  215000.0        NaN
2277       NaN  24.139579
2303       NaN  11.048029
2306       NaN  11.048029
2316       NaN  11.048029
2319      55.0        NaN
2323       NaN  11.048029
2324       NaN  11.048029
2330       NaN  11.048029
2333       NaN  11.048029
2334       NaN  11.048029
2335       NaN  11.048029
2336       NaN  11.048029
2337       NaN  11.048029
2338       NaN  11.048029
2339       NaN  11.048029
2340       NaN  11.048029
2341       NaN  11.048029
2342       NaN  11.048029
2343       NaN  11.048029
2344       NaN  11.048029
2345       NaN  11.048029
2346       NaN  11.048029
2347       NaN  11.048029
2350       NaN  24.308342
2368       NaN  11.048029
2409       NaN  11.048029
2410       NaN  11.048029
2411       NaN  11.048029
2412       NaN  11.048029
2413       NaN  11.048029
2414       NaN  11.048029
2415       NaN  11.048029
2416       NaN  11.048029
2417     219.0        NaN
2422       NaN  11.048029
2434       NaN  11.048029
2435       NaN  11.048029
2446       NaN  11.048029
2449       NaN  11.048029
2451       NaN  11.048029
2458       NaN  11.048029
2470    1500.0        NaN
2479   42000.0        NaN
2500       NaN  11.048029
2504   45500.0        NaN
2505       NaN  24.200666
2522       NaN  11.048029
2535       NaN  11.048029
2539       NaN  11.048029
2540       NaN  11.048029
2541       NaN  11.048029
2542       NaN  11.048029
2558       NaN  24.176544
2559       NaN  11.048029
2570       NaN  11.048029
2571       NaN  11.048029
2573       NaN  11.048029
2574       NaN  11.048029
2575       NaN  11.048029
2576       NaN  11.048029
2577       NaN  11.048029
2578       NaN  11.048029
2579       NaN  11.048029
2580       NaN  11.048029
2581       NaN  11.048029
2582       NaN  11.048029
2583       NaN  11.048029
2584       NaN  11.048029
2585       NaN  11.048029
2586       NaN  11.048029
2602       NaN  11.048029
2604       NaN  11.048029
2605       NaN  11.048029
2606       NaN  11.048029
2607       NaN  11.048029
2627       NaN  11.048029
2646     250.0        NaN
2655       NaN  11.048029
2665      55.0        NaN
2666       NaN  11.048029
2677   52000.0        NaN
2685  145000.0        NaN
2686       NaN  11.048029
2696     320.0        NaN
2700       NaN  11.048029
2710       NaN  11.048029
2712   15600.0        NaN
2714     650.0        NaN
2716       NaN  11.048029
2724       NaN  11.048029
2725       NaN  11.048029
2726       NaN  11.048029
2740  110250.0        NaN
2759  270000.0        NaN
2763       NaN  11.048029
2771     300.0        NaN
2780    1500.0        NaN
2796       NaN  11.048029
2797       NaN  11.048029
2798       NaN  11.048029
2799       NaN  11.048029
2800       NaN  11.048029
2801       NaN  11.048029
2806     300.0        NaN
2817   43000.0        NaN
2826       NaN  11.048029
2827       NaN  11.048029
2828       NaN  11.048029
2829       NaN  11.048029
2830       NaN  11.048029
2831       NaN  11.048029
2832       NaN  11.048029
2833       NaN  11.048029
2834       NaN  11.048029
2835       NaN  11.048029
2836       NaN  11.048029
2842       NaN  11.048029
2848   34999.0        NaN
2851       NaN  11.048029
2852       NaN  11.048029
2880       NaN  11.048029
2882       NaN  11.048029
2883   18890.0        NaN
2884   63000.0        NaN
2885       NaN  11.048029
2892       NaN  11.048029
2894       NaN  11.048029
2895       NaN  11.048029
2896       NaN  11.048029
2897       NaN  11.048029
2925   45000.0        NaN
2944       NaN  11.048029
2946       NaN  24.098350
2954       NaN  11.048029
2955       NaN  11.048029
2961       NaN  11.048029
2968       NaN  11.048029
2974       NaN  11.048029
2975       NaN  11.048029
3005       NaN  11.048029
3006       NaN  11.048029
3007       NaN  11.048029
3008       NaN  11.048029
3009       NaN  11.048029
3010       NaN  11.048029
3011       NaN  11.048029
3012       NaN  11.048029
3013       NaN  11.048029
3014       NaN  11.048029
3015       NaN  11.048029
3016       NaN  11.048029
3020       NaN  11.048029
3021       NaN  11.048029
3022       NaN  11.048029
3023       NaN  11.048029
3047   25000.0        NaN
3077     200.0        NaN
3080       NaN  11.048029
3081       NaN  11.048029
3082       NaN  11.048029
3083       NaN  11.048029
3084       NaN  11.048029
3085       NaN  11.048029
3086       NaN  11.048029
3087       NaN  11.048029
3088       NaN  11.048029
3093   41000.0        NaN
3135       NaN  11.048029
3136       NaN  11.048029
3137       NaN  11.048029
3138       NaN  11.048029
3139       NaN  11.048029
3144       NaN  24.109099
3152   72000.0        NaN
3155  175500.0        NaN
3165       NaN  11.048029
3166       NaN  11.048029
3167       NaN  11.048029
3168       NaN  11.048029
3169       NaN  11.048029
3170       NaN  11.048029
3171       NaN  11.048029
3172       NaN  11.048029
3173       NaN  11.048029
3174       NaN  11.048029
3175       NaN  11.048029
3176       NaN  11.048029
3177       NaN  11.048029
3208       NaN  24.150738
3221  185000.0        NaN
3227   98000.0        NaN
3233  125000.0        NaN
3235  135000.0        NaN
3258       NaN  11.048029
3259       NaN  11.048029
3267       NaN  11.048029
3268       NaN  11.048029
3275   93000.0        NaN
3287     600.0        NaN
3312       NaN  11.048029
3313       NaN  11.048029
3314       NaN  11.048029
3336       NaN  11.048029
3354   49600.0        NaN
3363   25000.0        NaN
3370       NaN  11.048029
3371       NaN  11.048029
3372       NaN  11.048029
3374       NaN  11.048029
3375       NaN  11.048029
3385  170000.0        NaN
3392  132000.0        NaN
3399       NaN  11.048029
3410     500.0        NaN
3412   18000.0        NaN
3415       NaN  11.048029
3436     100.0        NaN
3437   74900.0        NaN
3443   85500.0        NaN
3444  150735.0        NaN
3446     340.0        NaN
3450       NaN  11.048029
3487  309000.0        NaN
3499       NaN  11.048029
3507   40000.0        NaN
3509       NaN  11.048029
3515       NaN  11.048029
3522    1100.0        NaN
3525       NaN  11.048029
3526       NaN  11.048029
3527       NaN  11.048029
3528       NaN  11.048029
3535       NaN  11.048029
3536       NaN  11.048029
3537       NaN  11.048029
3539       NaN  11.048029
3540       NaN  11.048029
3542       NaN  11.048029
3543       NaN  11.048029
3544       NaN  11.048029
3552   63500.0        NaN
3553       NaN  11.048029
3554       NaN  11.048029
3555       NaN  11.048029
3564       NaN  11.048029
3565       NaN  11.048029
3566       NaN  11.048029
3567       NaN  11.048029
3568       NaN  11.048029
3569       NaN  11.048029
3570       NaN  11.048029
3586       NaN  11.048029
3589   30200.0        NaN
3593     650.0        NaN
3625       NaN  11.048029
3628       NaN  11.048029
3676       NaN  24.098147
3700       NaN  11.048029
3707       NaN  11.048029
3726   34000.0        NaN
3735   51000.0        NaN
3739   51000.0        NaN
3742   65500.0        NaN
3743   55000.0        NaN
3751       NaN  11.048029
3756   82830.0        NaN
3760       NaN  24.175559
3773       NaN  11.048029
3774     450.0        NaN
3793       NaN  11.048029
3804       NaN  11.048029
3807       NaN  11.048029
3808       NaN  11.048029
3809       NaN  11.048029
3853   41800.0        NaN
3855       NaN  11.048029
3870       NaN  11.048029
3873       NaN  11.048029
3895       NaN  11.048029
3899       NaN  11.048029
3917       NaN  11.048029
3940     550.0        NaN
3948       NaN  11.048029
3952       NaN  11.048029
3953       NaN  11.048029
3954       NaN  11.048029
3955       NaN  11.048029
3956       NaN  11.048029
3962   25500.0        NaN
3969   44000.0        NaN
3973    1200.0        NaN
3984   29999.0        NaN
3986       NaN  11.048029
4007     250.0        NaN
4009       NaN  11.048029
4010       NaN  11.048029
4011       NaN  11.048029
4025       NaN  11.048029
4026       NaN  11.048029
4037     550.0        NaN
4058       NaN  11.048029
4070       NaN  11.048029
4071       NaN  11.048029
4121     290.0        NaN
4124       NaN  11.048029
4126   26000.0        NaN
4156     500.0        NaN
4158   34999.0        NaN
4175       NaN  11.048029
4197     350.0        NaN
4212   42900.0        NaN
4213       NaN  11.048029
4267     260.0        NaN
4276       NaN  11.048029
4281     500.0        NaN
4286   81000.0        NaN
4288   42300.0        NaN
4295       NaN  11.048029
4296       NaN  11.048029
4315   50500.0        NaN
4318       NaN  11.048029
4325       NaN  11.048029
4369       NaN  11.048029
4382       NaN  11.048029
4387    1900.0        NaN
4396       NaN  11.048029
4407       NaN  11.048029
4424   30000.0        NaN
4425       NaN  11.048029
4431       NaN  11.048029
4446   16900.0        NaN
4451     290.0        NaN
4459       NaN  11.048029
4461       NaN  11.048029
4462       NaN  11.048029
4467       NaN        NaN
4476   63000.0        NaN
4479       NaN  11.048029
4490   59990.0        NaN
4493       NaN  11.048029
4494       NaN  24.176235
4496       NaN  11.048029
4503     300.0        NaN
4508     200.0        NaN
4510       NaN  11.048029
4523       NaN  11.048029
4528    1500.0        NaN
4546     650.0        NaN
4548       NaN  11.048029
4551   16500.0        NaN
4553   16500.0        NaN
4580       NaN  11.048029
4587     430.0        NaN
4590   80000.0        NaN
4599     650.0        NaN
4601       NaN  11.048029
4602       NaN  11.048029
4603       NaN  11.048029
4607   42900.0        NaN
4623  169900.0        NaN
4638       NaN  11.048029
4640       NaN  11.048029
4650       NaN  11.048029
4664       NaN  11.048029
4665       NaN  11.048029
4666       NaN  11.048029
4670   27500.0        NaN
4687   10445.0        NaN

array(['Brick-Panel', 'Panel', 'Wood', 'Masonry', 'Brick', nan,
       'Panel-Brick'], dtype=object)

In [ ]:
df_copy = df.copy()
num_vars_miss = ['price','lon']
cat_vars = ['op_type','condition']
for cat_var, num_var_miss in zip(cat_vars,num_vars_miss):
    for var_class in df[cat_var].unique():
        df_copy.update(df[df.loc[:,cat_var] == var_class][num_var_miss].replace(np.nan,df[df.loc[:,cat_var] == var_class][num_var_miss].mean()))

In [ ]:
df_copy[num_vars_miss].isnull().sum()

price    381
lon        0
dtype: int64